### ISSUE TITLE
play button

### ISSUE THREAD

**Issue by moha-b** [AndriaSalah/MusicPlayer-web#1] opened 2022-09-26 21:16 UTC
![save](https://user-images.githubusercontent.com/73842931/192381899-2cff281f-bff0-4e25-bf1b-4f57163afa31.png)

The play button does not return to its original state when you press it again, it just restarts the game

**Comment by AndriaSalah** [comment] 2022-09-28 06:30
the issue is now fixed , and now the track actually pauses if you press the playlist play button or plays depending on which state it was in before

**Closed as completed by AndriaSalah** 2022-09-28 06:30 UTC
